<?php
session_start();
include("../includes/db.php");
require_once("../engines/analytics_engine.php");

/* =========================
   AUTH CHECK
========================= */
if (!isset($_SESSION['user']) || $_SESSION['role'] !== 'admin') {
    die("Unauthorized access");
}

/* =========================
   RANGE (SAFE → CONVERT TO DATE RANGE)
========================= */
$range = isset($_GET['range']) ? (int)$_GET['range'] : 30;
$range = max(7, min(90, $range));

$startDate = date('Y-m-d', strtotime("-$range days"));
$endDate   = date('Y-m-d');

/* =========================
   LOAD DATA (NEW SYSTEM COMPATIBLE)
========================= */
$data = [

    /* GLOBAL KPIs */
    "revenue_kpi" => getRevenueKPI($conn),
    "conversion_kpi" => getConversionKPI($conn),

    /* DATE RANGE KPIs */
    "delivery_kpi" => getDeliveryKPI($conn, $startDate, $endDate),

    /* TREND DATA */
    "revenue_trend" => getRevenueTrend($conn, $startDate, $endDate),
    "orders_trend" => getOrdersTrend($conn, $startDate, $endDate),

    /* BREAKDOWN */
    "delivery_breakdown" => getDeliveryBreakdown($conn, $startDate, $endDate),

    /* INSIGHTS */
    "top_farmers" => getTopFarmers($conn)
];

/* =========================
   PDF LIBRARY
========================= */
require_once("../vendor/fpdf/fpdf.php");

$pdf = new FPDF();
$pdf->AddPage();

/* =========================
   HEADER SECTION (UPGRADED)
========================= */
$pdf->SetFont("Arial", "B", 18);
$pdf->Cell(0, 10, "FARM MARKETPLACE - BUSINESS INTELLIGENCE REPORT", 0, 1, "C");

$pdf->Ln(2);

$pdf->SetFont("Arial", "", 11);
$pdf->Cell(0, 8, "Report Period: Last $range Days", 0, 1, "C");
$pdf->Cell(0, 8, "Date Range: $startDate to $endDate", 0, 1, "C");
$pdf->Cell(0, 8, "Generated On: " . date("Y-m-d H:i:s"), 0, 1, "C");

$pdf->Ln(6);

/* =========================
   SUMMARY INSIGHT LINE
========================= */
$pdf->SetFont("Arial", "I", 10);

$insight =
    "Revenue: KES " . number_format($data['revenue_kpi']['total_revenue']) .
    " | Orders: " . $data['revenue_kpi']['total_orders'] .
    " | Delivery Success: " . $data['delivery_kpi']['success_rate'] . "%";

$pdf->Cell(0, 8, $insight, 0, 1, "C");

$pdf->Ln(8);

/* =========================
   FINANCIAL SECTION
========================= */
$pdf->SetFont("Arial", "B", 14);
$pdf->Cell(0, 10, "1. FINANCIAL PERFORMANCE", 0, 1);

$pdf->SetFont("Arial", "", 11);

$pdf->Cell(0, 8, "Total Revenue: KES " . number_format($data['revenue_kpi']['total_revenue'], 2), 0, 1);
$pdf->Cell(0, 8, "Total Orders: " . $data['revenue_kpi']['total_orders'], 0, 1);
$pdf->Cell(0, 8, "Average Order Value: KES " . number_format($data['revenue_kpi']['avg_order_value'], 2), 0, 1);
$pdf->Cell(0, 8, "Conversion Rate: " . $data['conversion_kpi']['conversion_rate'] . "%", 0, 1);

$pdf->Ln(6);

/* =========================
   DELIVERY SECTION
========================= */
$pdf->SetFont("Arial", "B", 14);
$pdf->Cell(0, 10, "2. DELIVERY PERFORMANCE", 0, 1);

$pdf->SetFont("Arial", "", 11);

$pdf->Cell(0, 8, "Total Deliveries: " . $data['delivery_kpi']['total_deliveries'], 0, 1);
$pdf->Cell(0, 8, "Delivered: " . $data['delivery_kpi']['delivered'], 0, 1);
$pdf->Cell(0, 8, "Success Rate: " . $data['delivery_kpi']['success_rate'] . "%", 0, 1);

$pdf->Ln(4);

/* =========================
   DELIVERY BREAKDOWN
========================= */
$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(0, 10, "Delivery Status Breakdown", 0, 1);

$pdf->SetFont("Arial", "", 11);

foreach ($data['delivery_breakdown'] as $d) {
    $pdf->Cell(0, 7, strtoupper($d['status']) . ": " . $d['total'], 0, 1);
}

$pdf->Ln(6);

/* =========================
   TOP FARMERS
========================= */
$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(0, 10, "Top Performing Farmers", 0, 1);

$pdf->SetFont("Arial", "", 11);

if (!empty($data['top_farmers'])) {
    foreach ($data['top_farmers'] as $f) {
        $pdf->Cell(
            0,
            7,
            $f['name'] . " - KES " . number_format($f['revenue'], 2),
            0,
            1
        );
    }
} else {
    $pdf->Cell(0, 7, "No farmer data available", 0, 1);
}

$pdf->Ln(8);

/* =========================
   FOOTER NOTE
========================= */
$pdf->SetFont("Arial", "I", 9);
$pdf->Cell(
    0,
    10,
    "This report is automatically generated by Farm Marketplace Analytics System",
    0,
    1,
    "C"
);

/* =========================
   OUTPUT
========================= */
$pdf->Output("D", "bi_report.pdf");
exit();
?>